version: '3.7'

services:
  db:
    container_name: error-budget-db
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: errorbudget
      PGDATA: /data/postgres
    volumes:
      - postgres-db:/data/postgres
      - ./data/schemas.sql:/docker-entrypoint-initdb.d/schemas.sql
    ports:
      - "5432:5432"

volumes:
  postgres-db:
    driver: local
